export const columns = [
  {
    fieldName: '_id',
    displayName: 'ProjectID',
    filter: { type: 'Checkbox' },
    width: '200px',
    visible: true,
  },
  {
    fieldName: 'clientName.name',
    displayName: 'Client',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'vessel_name.name',
    displayName: 'Vessel Name',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'vessel_type.name',
    displayName: 'Vessel Type',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'category.name',
    displayName: 'Category',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'building_type.name',
    displayName: 'Type Of Building',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'url',
    displayName: 'SharePOintLink',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'assigneeName',
    displayName: 'Assignee',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'est_start_date',
    displayName: 'Est. Start Date',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'targetDate',
    displayName: 'Est. End Date',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'createdAt',
    displayName: 'Actual Start Date',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'endDate',
    displayName: 'Actual End Date',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'stage.name',
    displayName: 'Stage',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
  {
    fieldName: 'status.name',
    displayName: 'Status',
    filter: { type: 'Checkbox' },
    width: '150px',
    visible: true,
  },
];
